### ISSUE TITLE
Application Unresponsive

### ISSUE THREAD

**Issue by DOWRIGHTTV** [DOWRIGHTTV/DNS-over-TLS-Relay#3]
Main function (Primary server/socket handler) hangs up and becomes unresponsive. no error or exception raised. Confirmed another thread is still active (tls queue handler).

**Comment by DOWRIGHTTV** [comment]
removed Main function from being called in a thread and is now running as part of main thread. So far stability seems to be improved.

**Comment by DOWRIGHTTV** [comment]
i lied. still an issue. :/ last test stayed up for 2.1 hours.

**Comment by VeryHardWorker** [comment]
I ran this for approx. 14 hours with the following result:
https://raw.githubusercontent.com/VeryHardWorker/DNS-over-TLS-Relay/master/testrun.md

Does that shed any light?

**Comment by DOWRIGHTTV** [comment]
Closing for now. It seems that OpenSSL lib was causing multiple low levels errors (double frees, double linked lists, segmentation faults) while running. Putting a small delay between TLS socket receive and send in the TLS handler section seemed to have resolved the issue.
